version: '3'

services:
  json:
    build:
      context: .
      dockerfile: ./benchmarker.dockerfile
    environment:
      FORMAT: "JSON"
      PORT: 2001
      MULTICAST_HOST: "224.0.0.1"
      MULTICAST_PORT: 2023

  xml:
    build:
      context: .
      dockerfile: ./benchmarker.dockerfile
    environment:
      FORMAT: "XML"
      PORT: 2002
      MULTICAST_HOST: "224.0.0.1"
      MULTICAST_PORT: 2023

  msgpack:
    build:
      context: .
      dockerfile: ./benchmarker.dockerfile
    environment:
      FORMAT: "MSGPACK"
      PORT: 2003
      MULTICAST_HOST: "224.0.0.1"
      MULTICAST_PORT: 2023

  yaml:
    build:
      context: .
      dockerfile: ./benchmarker.dockerfile
    environment:
      FORMAT: "YAML"
      PORT: 2004
      MULTICAST_HOST: "224.0.0.1"
      MULTICAST_PORT: 2023

  native:
    build:
      context: .
      dockerfile: ./benchmarker.dockerfile
    environment:
      FORMAT: "NATIVE"
      PORT: 2005
      MULTICAST_HOST: "224.0.0.1"
      MULTICAST_PORT: 2023

  proxy:
    build:
      context: .
      dockerfile: ./proxy.dockerfile
    expose:
      - "2000/udp"
    ports:
      - "2000:2000/udp"
    environment:
      PORT: 2000
      JSON_PORT: 2001
      XML_PORT: 2002
      MSGPACK_PORT: 2003
      YAML_PORT: 2004
      NATIVE_PORT: 2005
      MULTICAST_HOST: "224.0.0.1"
      MULTICAST_PORT: 2023
    depends_on:
      - json
      - xml
      - msgpack
      - yaml
      - native